# -*- coding: utf-8 -*-
"""
v1.0.38 主密碼設定工具

本機跑這支腳本一次，產生 _secret.py（密碼 hash + 隨機 salt）。
_secret.py 已被 .gitignore 排除，不會進 repo。
編 EXE 時 PyInstaller 會把 _secret.py 嵌進去。

使用：
    python set_master_password.py
或雙擊：
    set_master_password.bat
"""
import os
import sys
import hashlib
import secrets
import getpass

ITERATIONS = 200000


def main():
    print("=" * 56)
    print(" HIV 取號工具 — 主密碼設定")
    print("=" * 56)
    print()
    print(" 這個密碼會被 PyInstaller 嵌入下次編出的 EXE。")
    print(" 不論在哪台電腦執行 EXE，都只接受這組密碼。")
    print(" 改密碼 → 重跑這支 → 重新編譯。")
    print()
    print(" 雜湊：PBKDF2-HMAC-SHA256 / 200000 輪 / 隨機 16 byte salt")
    print()

    p1 = getpass.getpass(" 請輸入主密碼（至少 6 字元）：")
    if len(p1) < 6:
        print(" ✗ 密碼至少 6 字元")
        sys.exit(1)
    p2 = getpass.getpass(" 再輸入一次以確認：    ")
    if p1 != p2:
        print(" ✗ 兩次輸入不一致")
        sys.exit(1)

    salt = secrets.token_bytes(16)
    h = hashlib.pbkdf2_hmac("sha256", p1.encode("utf-8"), salt, ITERATIONS).hex()

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_secret.py")
    content = (
        "# Auto-generated by set_master_password.py — DO NOT COMMIT\n"
        "# 請保持本檔在 .gitignore 內\n"
        f'MASTER_PASSWORD_HASH = "{h}"\n'
        f'MASTER_PASSWORD_SALT_HEX = "{salt.hex()}"\n'
        f"PBKDF2_ITERATIONS = {ITERATIONS}\n"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)

    print()
    print(f" ✓ 已產生 {out_path}")
    print(" ✓ 接著執行 build_release.bat 編譯 EXE。")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n 已取消")
        sys.exit(1)
